# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status_point', '0004_auto_20160307_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='status_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_detail', to='status_point.StatusPoint'),
        ),
    ]
