# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_point', '0005_auto_20160307_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='url_id',
        ),
        migrations.AddField(
            model_name='indicator',
            name='url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
