# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_point', '0006_auto_20160307_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspoint',
            name='overall_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='statuspoint',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='statuspoint',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='statuspoint',
            name='contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='statuspoint',
            name='indicator_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='statuspoint',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='statuspoint',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='statuspoint',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='statuspoint',
            name='phone',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='statuspoint',
            name='short_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
